[workspace]
authors = ["Haotian Yi <yi54@illinois.edu>"]
channels = ["conda-forge"]
name = "data-specification"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
graph-tool = ">=2.98,<3"
pandas = ">=2.3.3,<3"
networkit = ">=11.1,<12"
leidenalg = ">=0.10.2,<0.11"
git = ">=2.51.0,<3"

[pypi-dependencies]
treeswift = ">=1.1.45, <2"
cython = ">=3.1.4, <4"
attrs = ">=25.4.0, <26"
click = ">=8.3.0, <9"
colorama = ">=0.4.6, <0.5"
coloredlogs = ">=15.0.1, <16"
exceptiongroup = ">=1.3.0, <2"
graphviz = ">=0.21, <0.22"
heapdict = ">=1.0.1, <2"
humanfriendly = ">=10.0, <11"
igraph = "*"
iniconfig = ">=2.1.0, <3"
jsonpickle = ">=4.1.1, <5"
leidenalg = "*"
numpy = "*"
packaging = "*"
pandas = "*"
pip = "*"
pluggy = ">=1.6.0, <2"
pytest = ">=8.4.2, <9"
pytz = "*"
scipy = "*"
setuptools = "*"
six = "*"
structlog = ">=25.4.0, <26"
tomli = ">=2.3.0, <3"
typer = ">=0.19.2, <0.20"
typing-extensions = ">=4.15.0, <5"
networkx = ">=3.5, <4"
psutil = ">=7.1.0, <8"
infomap = ">=2.8.0, <3"
networkit = "*"

hm01 = { path = "./downloaded_programs/cm_pipeline" }
pymincut = { git = "https://github.com/AnoldGH/python-mincut" }
